var _vaccination_repository_interface_8java =
[
    [ "com.mycompany.schronisko.respositories.VaccinationRepositoryInterface", "interfacecom_1_1mycompany_1_1schronisko_1_1respositories_1_1_vaccination_repository_interface.html", "interfacecom_1_1mycompany_1_1schronisko_1_1respositories_1_1_vaccination_repository_interface" ]
];